### ISSUE TITLE
Upgrader: Database error, given array of integer values is empty. (member_list)

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7073]
#### Description
```
+++  Moving label info to new tables and updating rules (May be slow!!!)Error: Database error, given array of integer values is empty. (member_list)<em>(upgrade.php(2148) : eval()'d code-74)</em> File: yada\yada\Sources\Subs-Db-mysql.php Line: 930<div style='color:#e74c3c;margin:20px 0px 20px 0px;padding:0px 10px 20px 10px;border:solid 1px #e74c3c;border-radius:4px;'>
Fatal error: Uncaught Error: Call to undefined function allowedTo() in yada\yada\Sources\Subs-Db-mysql.php:705
Stack trace:
#0 yada\yada\Sources\Subs-Db-mysql.php(491): smf_db_error('\n\t\t\t\tUPDATE smf...', Object(mysqli))
#1 yada\yada\upgrade.php(2148) : eval()'d code(74): smf_db_query('', '\n\t\t\t\tUPDATE smf...', Array)
#2 yada\yada\upgrade.php(2148): eval()
#3 yada\yada\upgrade.php(1641): parse_sql('D:\\EasyPHP\\van2...')
#4 yada\yada\upgrade.php(350): DatabaseChanges()
#5 {main}
  thrown in yada\yada\Sources\Subs-Db-mysql.php on line 705
```

### Steps to reproduce
1. Upgrade a 2.0 DB via CLI

### Environment (complete as necessary)
- Version/Git revision:  Current
- Database Type:  Mysql
- Database Version:  5.7
- PHP Version:  7.4

**Comment by sbulen** [comment]
At first glance, this appears related to #7019 

In this particular test DB there are no PMs at all; this may be part of it.  

The SQL query being generated looks like:
```
UPDATE smf_pm_recipients
SET in_inbox = 1
WHERE FIND_IN_SET(-1, labels)
AND id_member IN ()
```

@BrickOzp - could you take a peek at this?

**Comment by BrickOzp** [comment]
@sbulen Please test this fix

**Comment by sbulen** [comment]
Thanx!  Will take a peek tomorrow.
