### ISSUE TITLE
Upgrader: Fatal error: Uncaught Error: Value of type null is not callable in iri_to_url

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7090]
#### Description

Doing a simple 2.0=>2.1 upgrade via CLI:
```
Fatal error: Uncaught Error: Value of type null is not callable in yada\yada\Sources\Subs.php:7598
Stack trace:
#0 yada\yada\Sources\Subs.php(5769): iri_to_url('https://www.sim...')
#1 yada\yada\upgrade.php(1840): fetch_web_data('https://www.sim...')
#2 yada\yada\upgrade.php(1757): cli_scheduled_fetchSMfiles()
#3 yada\yada\upgrade.php(3364): DeleteUpgrade()
#4 yada\yada\upgrade.php(3693): ConvertUtf8()
#5 yada\yada\upgrade.php(357): serialize_to_json()
#6 {main}
  thrown in yada\yada\Sources\Subs.php on line 7598

```
### Steps to reproduce
1. Upgrade 2.0 => 2.1

### Environment (complete as necessary)
- Version/Git revision:  Current as of NOW
- Database Type:  Mysql
- Database Version: 5.7
- PHP Version: 8.0

### Additional information/references
Error is slightly different under php7.4:
`Fatal error: Uncaught Error: Function name must be a string in yada\yada\Sources\Subs.php:7598`

**Comment by sbulen** [comment]
@Sesquipedalian - Could you take a look at this?
