### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError: Too few arguments to function SMF\Config::updateModSettings()

### ISSUE THREAD

**Issue by tinoest** [SimpleMachines/SMF#7872]
#### Description
Fatal error: Uncaught ArgumentCountError: Too few arguments to function SMF\Config::updateModSettings(), 0 passed in /var/www/html/Sources/Config.php(1001) : eval()'d code on line 1 and at least 1 expected in /var/www/html/Sources/Config.php:1253 

Stack trace: 
#0 /var/www/html/Sources/Config.php(1001) : eval()'d code(1): SMF\Config::updateModSettings() 
#1 /var/www/html/TinyPortal/Integrate.php(107): updateSettings(Array) 
#2 [internal function]: TinyPortal\Integrate::hookPreLoad()
#3 /var/www/html/Sources/IntegrationHook.php(130): call_user_func_array(Array, Array) 
#4 /var/www/html/Sources/IntegrationHook.php(187): SMF\IntegrationHook->execute(Array) 
#5 /var/www/html/Sources/Config.php(1232): SMF\IntegrationHook::call('integrate_pre_l...') 
#6 /var/www/html/Sources/Forum.php(206): SMF\Config::reloadModSettings() 
#7 /var/www/html/index.php(130): SMF\Forum->__construct() 
#8 {main} thrown in /var/www/html/Sources/Config.php on line 1253

### Steps to reproduce
1. Install TinyPortal
2. See Error Log, the eval function on 1001 isn't massing a parameter to the static function

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by tinoest** [comment]
```
eval('function updateSettings($change, $update = false) { return ' . __CLASS__ . '::updateModSettings($change, $update); }');
```

I think that is what you wanted to do.
